import * as yaml from 'js-yaml';
import localesMetadataYaml from '../locales/metadata.yaml?raw';

// Parse metadata and extract language configuration
function parseYaml(yamlString) {
  return yaml.load(yamlString);
}

const metadata = parseYaml(localesMetadataYaml);

// Auto-discover supported locales from metadata
export const SUPPORT_LOCALES = Object.keys(metadata);
export const DEFAULT_LOCALE = 'en';
export const LOCALE_STORAGE_KEY = 'dbdiagram-locale';

// Export language metadata for frontend use
export const languageMetadata = metadata;

// Import pre-built merged locale files (generated by scripts/build-locales.cjs)
// These files are built from locales/{locale}/*.yaml
import enMessages from '../dist/en.json' with { type: 'json' };
import viMessages from '../dist/vi.json' with { type: 'json' };
import zhMessages from '../dist/zh.json' with { type: 'json' };
import jaMessages from '../dist/ja.json' with { type: 'json' };

// Build messages with namespaces
export const messages = {
  en: enMessages,
  vi: viMessages,
  zh: zhMessages,
  ja: jaMessages,
};

// NOTE: To add a new language:
// 1. Create a new folder in locales/ (e.g., ja/, fr/)
// 2. Copy translation YAML files from an existing language
// 3. Add the language to locales/metadata.yaml with flag, hello, name, nativeName
// 4. Run `yarn build` to regenerate the merged JSON files
